Repository greedy-team/zup-zup-fe, pull requests merged in 2025-09, with the labels that each got.

#67 Feat/#46 분실물 등록 프로세스 반응형 UI 구현 및 본 서버 API 연결
  src/api/register/index.ts
  src/component/common/ProgressBar.tsx
  src/component/common/ResultModal.tsx
  src/constants/register/index.ts
  src/hooks/register/useRegisterProcess.ts
  src/mocks/seeds/categories.seed.ts
  src/pages/register/RegisterCategory.tsx
  src/pages/register/RegisterDetails.tsx
  src/pages/register/RegisterLayout.tsx
  src/pages/register/RegisterReview.tsx
  src/types/register/index.ts
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#69 Feat/#66 UX 고려하여 로그인 페이지 구현 (반응형)
  assets/loginLogo.png
  src/App.tsx
  src/api/auth/index.ts
  src/api/common/apiClient.ts
  src/component/root/layout/Authentication.tsx
  src/contexts/AuthFlag.tsx
  src/pages/login/LoginPage.tsx
  src/utils/auth/loginRedirect.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#113 refactor #96: 학교 바깥부분 마스킹
  src/constants/map/mapConfig.ts
  src/constants/map/polygonStyle.ts
Labels: 🎨 Html&css, 🔨 Refactor
