Repository greedy-team/zup-zup-fe, pull requests merged in 2025-08, with the labels that each got.

#16 Feat/#6 메인 페이지 mock 서버 구현(MSW)
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/db/categories.db.ts
  src/mocks/db/features.db.ts
  src/mocks/db/lostItems.db.ts
  src/mocks/db/schoolAreas.db.ts
  src/mocks/handlers.ts
  src/mocks/handlers/categories.handlers.ts
  src/mocks/handlers/lostItems.handlers.ts
  src/mocks/handlers/schoolAreas.handlers.ts
  src/mocks/seeds/categories.seed.ts
  src/mocks/seeds/features.seed.ts
  src/mocks/seeds/lostItems.seed.ts
  src/mocks/seeds/schoolAreas.seed.ts
  src/mocks/seeds/seedAll.ts
  src/mocks/selectors/categories.selectors.ts
  src/mocks/selectors/lostItems.selectors.ts
  src/mocks/selectors/schoolAreas.selectors.ts
Labels: ✨ Feature

#13 Feature/#4 mainPage 구현
  package-lock.json
  package.json
  src/component/main/header.tsx
  src/component/main/header/header.tsx
  src/component/main/main/list.tsx
  src/component/main/main/lostList.tsx
  src/component/main/main/lostListItem.tsx
  src/component/main/main/main.tsx
  src/component/main/main/map.tsx
  src/component/main/modal/registerConfirmModal.tsx
  src/pages/mainPage.tsx
  src/tests/main/List.test.tsx
  src/tests/main/Main.test.tsx
  src/tests/main/RegisterConfirmModal.test.tsx
  src/types/main/category.d.ts
  src/vite-env.d.ts
Labels: ✨ Feature

#20 feat: 글로벌 폰트 적용
  src/assets/fonts/Moneygraphy-Rounded.woff
  src/assets/fonts/Moneygraphy-Rounded.woff2
  src/assets/fonts/fonts.css
  src/index.css
Labels: ✨ Feature, 🎨 Html&css

#17 Feat/#7 찾기 페이지 mock 서버 구현(MSW)
  src/mocks/handlers/pledge.handlers.ts
  src/mocks/selectors/pledge.selectors.ts
Labels: ⚙ Setting, ✨ Feature

#27 Chore/#26 Mock 서버 Seed 데이터(학교 구역, 분실물) 보완
  src/mocks/seeds/features.seed.ts
  src/mocks/seeds/lostItems.seed.ts
  src/mocks/seeds/schoolAreas.seed.ts
Labels: ⚙ Setting

#28 Feature/#24 Mock 서버 분실물 등록 Modal에 연결
  src/api/register/index.ts
  src/component/main/main/main.tsx
  src/component/main/main/map.tsx
  src/component/register/RegisterModal.tsx
  src/component/register/steps/Step1_CategorySelect.tsx
  src/component/register/steps/Step2_DetailForm.tsx
  src/component/register/steps/Step3_Confirm.tsx
  src/constants/register/index.ts
  src/hooks/register/useRegisterProcess.ts
  src/tests/register/RegisterModal.test.tsx
  src/tests/register/api/register.test.ts
  src/tests/register/hooks/useRegisterProcess.test.ts
  src/tests/register/steps/Step1_CategorySelect.test.tsx
  src/tests/register/steps/Step2_DetailForm.test.tsx
  src/tests/register/steps/Step3_Confirm.test.tsx
  src/types/register/index.ts
Labels: 📬 API, 🔨 Refactor, ✅ Test

#58 feat/#56: 지도 api관련 로직 구현
  assets/numberedPin/number-1.png
  assets/numberedPin/number-10.png
  assets/numberedPin/number-2.png
  assets/numberedPin/number-3.png
  assets/numberedPin/number-4.png
  assets/numberedPin/number-5.png
  assets/numberedPin/number-6.png
  assets/numberedPin/number-7.png
  assets/numberedPin/number-8.png
  assets/numberedPin/number-9.png
  src/apis/main/mainApi.tsx
  src/component/main/header/CategoryRadio.tsx
  src/component/main/header/Header.tsx
  src/component/main/main/Main.tsx
  src/component/main/main/Map.tsx
  src/component/main/main/list/LostList.tsx
  src/component/main/main/list/LostListItem.tsx
  src/component/main/main/list/Pagenation.tsx
  src/component/main/modal/RegisterConfirmModal.tsx
  src/constants/main/pagenation.ts
  src/constants/map/mapConfig.ts
  src/constants/map/numberedPinImage.ts
  src/constants/map/polygonStyle.ts
  src/hooks/map/getKakaoMap.ts
  src/hooks/map/useHardLock.ts
  src/hooks/map/useNumberedMarkers.ts
  src/hooks/map/useOutsideMask.ts
  src/hooks/map/usePolygons.ts
  src/hooks/map/useRegisterMapClick.ts
  src/pages/main/MainPage.tsx
  src/types/global.d.ts
  src/types/main/components.d.ts
  src/utils/Map/mapUtils.ts
  src/utils/Page/pagenationUtils.ts
  src/utils/isValidId.ts
Labels: ✨ Feature, 📬 API, 🔨 Refactor
